
export enum ActionType {
    BACKEND_API_REQUEST = 'BACKEND_API_REQUEST',
    BACKEND_API_REQUEST_FAILURE = 'BACKEND_API_REQUEST_FAILURE',

    UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS',
    GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS'
    
  }